"""review-dates

Revision ID: 154a5273fdae
Revises: c28a391b8109
Create Date: 2022-06-09 11:04:09.798693

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '154a5273fdae'
down_revision = 'c28a391b8109'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'created_at',
                    existing_type=sa.DATETIME(),
                    type_=sa.String(length=100),
                    nullable=False)
    op.alter_column('reviews', 'updated_at',
                    existing_type=sa.DATETIME(),
                    type_=sa.String(length=100),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('reviews', 'created_at',
                    existing_type=sa.String(length=100),
                    type_=sa.DATETIME(),
                    nullable=True)
    op.alter_column('reviews', 'updated_at',
                    existing_type=sa.String(length=100),
                    type_=sa.DATETIME(),
                    nullable=True)
    # ### end Alembic commands ###
