"""total-type-change-orders-table

Revision ID: 75f2795c1173
Revises: 2bdd15f46ec1
Create Date: 2022-06-11 18:56:17.487238

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '75f2795c1173'
down_revision = '2bdd15f46ec1'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'total',
               existing_type=sa.NUMERIC(precision=10, scale=2),
               type_=sa.String(length=20),
               existing_nullable=False)
    op.alter_column('products', 'image_url',
               existing_type=sa.VARCHAR(length=500),
               type_=sa.String(length=1000),
               existing_nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('products', 'image_url',
               existing_type=sa.String(length=1000),
               type_=sa.VARCHAR(length=500),
               existing_nullable=False)
    op.alter_column('orders', 'total',
               existing_type=sa.String(length=20),
               type_=sa.NUMERIC(precision=10, scale=2),
               existing_nullable=False)
    # ### end Alembic commands ###
