"""revise-order-table

Revision ID: 8e0728e5d61d
Revises: b511e590df1b
Create Date: 2022-06-06 21:51:21.563490

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8e0728e5d61d'
down_revision = 'b511e590df1b'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('order_number', sa.String(length=100), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'order_number')
    # ### end Alembic commands ###
