"""order-created-at

Revision ID: c28a391b8109
Revises: 919bf369090e
Create Date: 2022-06-08 12:42:45.420677

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'c28a391b8109'
down_revision = '919bf369090e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
                    existing_type=sa.DATE(),
                    type_=sa.String(length=100),
                    nullable=False)
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('orders', 'created_at',
                    existing_type=sa.String(length=100),
                    type_=sa.DATE(),
                    nullable=True)
    # ### end Alembic commands ###
