"""revise-orders-table

Revision ID: 3d9e652539ef
Revises: 3f118596b001
Create Date: 2022-06-11 16:08:38.786570

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3d9e652539ef'
down_revision = '3f118596b001'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('orders', sa.Column('full_name', sa.String(length=100), nullable=False))
    op.add_column('orders', sa.Column('phone', sa.String(length=20), nullable=False))
    op.add_column('orders', sa.Column('address', sa.String(length=255), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'address')
    op.drop_column('orders', 'phone')
    op.drop_column('orders', 'full_name')
    # ### end Alembic commands ###
